namespaces:
- o
- hr
- cs
- .cz
- pl
- .pl
- eo
- de
- .de
- pka
- dcm
- lge
- github: texttheater
- name: emb
  shortcuts:
    test 0: https://www.test.de/
    eau 1:
      include: 
        key: e 1
        namespace: .au 
# - github: .
language: de
country: de
defaultKeyword: g
