namespaces:
- o
- hr
- cs
- .cz
- pl
- .pl
- eo
- de
- .de
- pka
- dcm
- lge
- github: texttheater
- url: https://jaehnig.org/shortcuts.yml
- name: embedded
  shortcuts:
    test 0: https://www.test.de/
- github: .
language: de
country: de
defaultKeyword: g
